# Generated by Django 2.2.1 on 2019-05-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120)),
                ('Description', models.CharField(max_length=120)),
                ('DateTime_of_todo_task', models.DateTimeField()),
                ('Status', models.CharField(choices=[('progress', 'progress'), ('completed', 'completed'), ('pending', 'pending')], max_length=25)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
